
# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf


################
### PROGRAMS ###
################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$fileManager = nautilus
$menu = anyrun || pgrep anyrun && pkill anyrun
$browser = /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=launch-script.sh --file-forwarding app.zen_browser.zen
$lockscreen = hyprlock
$cursorTheme = Layan-white-cursors

#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = hyprpm reload -nn
exec-once = hyprctl setcursor $cursorTheme 20
# exec-once = waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css
exec-once = ashell
exec-once = wpaperd
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$cursorTheme'
exec-once = hyprswitch init --show-title &
exec-once = syshud
exec-once = walker --gapplication-service
permission = /usr/bin/hyprpm, plugin, allow

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XDG_CURRENT_DESKTOP,Hyprland
env = XCURSOR_SIZE,20
env = HYPRCURSOR_SIZE,20
env = GDK_SCALE,1.2
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland,x11
env = CLUTTER_BACKEND,wayland,x11
env = LIBVA_DRIVER_NAME,nvidia

############
### RICE ###
############

source = ~/.config/hypr/rice.conf


################
### PLUGINS ###
################

source = ~/.config/hypr/plugins.conf

###############
### DEVICES ###
###############

source = ~/.config/hypr/devices.conf


#############
### INPUT ###
#############

source = ~/.config/hypr/keybinds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ~/.config/hypr/window.conf

